% +UTIL
% 
%   Contents file for +UTIL and its subfolders.
%   
%   +UTIL
%   bfra.util.numevents - Count the number of events in struct returned by bfra.getevents
%   bfra.util.numfits   - Count the number of fits in struct returned by bfra.fitevents
%   bfra.util.numtau    - Count the number of tau values in struct returned by bfra.fitevents
%    
%   This file was generated by updatecontents.m on 06 Sep 2023 at 15:36:12.
