% +TEST
% 
%   Contents file for +TEST and its subfolders.
%   
%   +TEST
%   baseflow.test.runtests         - Run all tests in the baseflow.test package
%   baseflow.test.test_conversions - Test baseflow.conversions
%   baseflow.test.test_islocalmax  - Test baseflow/private/islocalmax.m
%   baseflow.test.test_todatenum   - Test baseflow/private/todatenum
%   baseflow.test.test_withcd      - Test withcd
%   baseflow.test.TestBaseflow     - Test the baseflow toolbox
%    
%   This file was generated by updatecontents.m on 06 Sep 2023 at 15:36:12.
