classdef test_conversions < matlab.unittest.TestCase
   %TEST_CONVERSIONS Test baseflow.conversions.

   properties (TestParameter)
      % Flat-aquifer conversions. Each case holds the input value, the input
      % and output parameter names, and the formula for the expected output
      % value. The b = 1 and b = 2 cases give infinite alpha, beta, and d.
      flatcase = struct( ...
         'b_to_n', {{1.5, 'b', 'n', @(b) (3-2.*b)./(b-2)}}, ...
         'n_to_b', {{1.5, 'n', 'b', @(n) (2.*n+3)./(n+2)}}, ...
         'b_to_d', {{2.0, 'b', 'd', @(b) 1./(2-b)}}, ...
         'b_to_k', {{1.4, 'b', 'k', @(b) (1-b)./(b-2)}}, ...
         'k_to_b', {{2/3, 'k', 'b', @(k) (2.*k+1)./(k+1)}}, ...
         'b_to_N', {{1.5, 'b', 'N', @(b) 3-2.*b}}, ...
         'b_to_alpha', {{1.0, 'b', 'alpha', @(b) 1./(b-1)}}, ...
         'b_to_beta', {{2.0, 'b', 'beta', @(b) 1./(b-2)}}, ...
         'b_to_gamma', {{1.5, 'b', 'gamma', @(b) 1./(2.*b-3)}})

      % Bad inputs. Each case holds the input value, the input parameter
      % name, and the expected error identifier: a non-numeric inputvalue,
      % a non-char inputvarname, and an unsupported inputvarname.
      badinput = struct( ...
         'nonnumeric_value', {{'string', 'b', ...
         'MATLAB:InputParser:ArgumentFailedValidation'}}, ...
         'nonchar_varname', {{1.5, 123, ...
         'MATLAB:unrecognizedStringChoice'}}, ...
         'unsupported_varname', {{1.5, 'unsupported', ...
         'MATLAB:unrecognizedStringChoice'}})
   end

   methods (Test)
      function test_convert2b(testCase, flatcase)
         % Test the conversions from one parameter to another for the
         % 'isflat' condition
         tolerance = 0.001;
         [inputvalue, inputname, outputname, formula] = flatcase{:};

         returned = baseflow.conversions(inputvalue, inputname, ...
            outputname, 'isflat', true);
         expected = formula(inputvalue);
         testCase.verifyEqual(returned, expected, 'AbsTol', tolerance, ...
            sprintf('Failed to convert %s to %s correctly', ...
            inputname, outputname));
      end

      function test_errorThrownForBadInput(testCase, badinput)
         % Verify that the function throws an error for each bad input
         [inputvalue, inputname, expected] = badinput{:};
         testCase.verifyError( ...
            @() baseflow.conversions(inputvalue, inputname, 'n'), expected);
      end
   end
end
