classdef test_eqstrings < matlab.unittest.TestCase
   %TEST_EQSTRINGS Test the equation label helpers.
   %
   % The suite checks baseflow.aQbString, baseflow.QtString, and
   % baseflow.QtauString. Each helper returns two labels. The expected
   % labels below follow the output order of each helper.
   %
   % See also: baseflow.aQbString, baseflow.QtString, baseflow.QtauString

   properties (TestParameter)
      % Labels with values. Each case holds the helper, its positional
      % inputs, and the expected first and second outputs. The [1e-2 1.5]
      % cases use the symbolic Q0 or tau0. The [1250 2] cases check the
      % mantissa for a >= 10 and a numeric Q0 or tau0. Every case checks
      % that math mode closes before e, so e is upright.
      valuecase = struct( ...
         'aQbString_small_a', {{@baseflow.aQbString, {[1e-2 1.5]}, ...
         '-d$Q$/d$t$ = 1e$^{-2}Q^{1.50}$', ...
         '$Q(t) = [Q_0^{-(b-1)}+a(b-1)t]^{-1/(b-1)} (b=1.50)$'}}, ...
         'aQbString_large_a', {{@baseflow.aQbString, {[1250 2], 1000}, ...
         '-d$Q$/d$t$ = 1e$^{3}Q^{2.00}$', ...
         '$Q(t) = [1000^{-(b-1)}+a(b-1)t]^{-1/(b-1)} (b=2.00)$'}}, ...
         'QtString_small_a', {{@baseflow.QtString, {[1e-2 1.5]}, ...
         '$Q(t) = [Q_0^{-(b-1)}+a(b-1)t]^{-1/(b-1)} (b=1.50)$', ...
         '-d$Q$/d$t$ = 1e$^{-2}Q^{1.50}$'}}, ...
         'QtString_large_a', {{@baseflow.QtString, {[1250 2], 1000}, ...
         '$Q(t) = [1000^{-(b-1)}+a(b-1)t]^{-1/(b-1)} (b=2.00)$', ...
         '-d$Q$/d$t$ = 1e$^{3}Q^{2.00}$'}}, ...
         'QtauString_small_a', {{@baseflow.QtauString, {[1e-2 1.5]}, ...
         '$Q^* = [\tau$/$\tau_0$]$^{-\alpha}$ $(b=1.50)$', ...
         '-d$Q$/d$t$ = 1e$^{-2}Q^{1.50}$'}}, ...
         'QtauString_large_a', {{@baseflow.QtauString, {[1250 2], 5}, ...
         '$Q^* = [\tau$/5]$^{-\alpha}$ $(b=2.00)$', ...
         '-d$Q$/d$t$ = 1e$^{3}Q^{2.00}$'}})

      % Symbolic labels. Each case holds the helper and the expected first
      % and second outputs. The aQb and Q(t) labels equal the
      % baseflow.getstring labels.
      symboliccase = struct( ...
         'aQbString', {{@baseflow.aQbString, ...
         '$-\mathrm{d}Q/\mathrm{d}t = aQ^b$', ...
         '$Q(t) = [Q_0^{-(b-1)}+a(b-1)t]^{-1/(b-1)}$'}}, ...
         'QtString', {{@baseflow.QtString, ...
         '$Q(t) = [Q_0^{-(b-1)}+a(b-1)t]^{-1/(b-1)}$', ...
         '$-\mathrm{d}Q/\mathrm{d}t = aQ^b$'}}, ...
         'QtauString', {{@baseflow.QtauString, ...
         '$Q^* = [\tau$/$\tau_0$]$^{-\alpha}$', ...
         '$-\mathrm{d}Q/\mathrm{d}t = aQ^b$'}})
   end

   methods (Test)
      function test_valuelabels(testCase, valuecase)
         % Verify both labels when 'printvalues' is true
         [helper, inputs, first_expected, second_expected] = valuecase{:};

         [first_returned, second_returned] = helper(inputs{:}, ...
            'printvalues', true);

         testCase.verifyEqual(first_returned, first_expected)
         testCase.verifyEqual(second_returned, second_expected)
      end

      function test_symboliclabels(testCase, symboliccase)
         % Verify both labels when 'printvalues' is false (the default).
         % The [a b] values must not appear in the labels.
         [helper, first_expected, second_expected] = symboliccase{:};

         [first_returned, second_returned] = helper([1e-2 1.5]);

         testCase.verifyEqual(first_returned, first_expected)
         testCase.verifyEqual(second_returned, second_expected)
      end
   end
end
