classdef test_nanstats < matlab.unittest.TestCase
   %TEST_NANSTATS Test the private nanmean and nanmedian helpers.
   %
   % nanmean and nanmedian are private, so the tests reach them with
   % baseflow.privatefunction. Private functions take precedence over any
   % nanmean or nanmedian on the path. Expected values are hand-computed
   % means and medians of the non-NaN elements. The tests cover vector and
   % matrix shapes, dimension arguments, output types, all-NaN and empty
   % inputs, and the input-count errors.

   properties (TestParameter)
      % nanmean cases. Each case holds the input arguments and the expected
      % mean. nanmean ignores NaN elements in column and row vectors. A
      % matrix averages down columns by default, along DIM when given, and
      % over every element with 'all' or VECDIM. OUTTYPE sets the class of
      % the result, alone and after DIM. All-NaN and empty inputs return NaN
      % with the reduced size.
      meancase = struct( ...
         'column', {{{[1; NaN; 3]}, (1 + 3)/2}}, ...
         'row', {{{[2, NaN, 4, 6]}, (2 + 4 + 6)/3}}, ...
         'matrixDefaultDim', {{{[1, NaN; 3, 4; NaN, 8]}, ...
         [(1 + 3)/2, (4 + 8)/2]}}, ...
         'matrixDim2', {{{[1, NaN; 3, 4; NaN, 8], 2}, ...
         [1; (3 + 4)/2; 8]}}, ...
         'matrixAll', {{{[1, NaN; 3, 4; NaN, 8], 'all'}, ...
         (1 + 3 + 4 + 8)/4}}, ...
         'matrixVecdim', {{{[1, NaN; 3, 4; NaN, 8], [1, 2]}, ...
         (1 + 3 + 4 + 8)/4}}, ...
         'nativeType', {{{int8([1, 2]), 'native'}, int8((1 + 2)/2)}}, ...
         'doubleType', {{{int8([1, 2]), 'double'}, (1 + 2)/2}}, ...
         'defaultType', {{{int8([1, 2]), 'default'}, (1 + 2)/2}}, ...
         'dimDoubleType', {{{single([1, NaN, 3]), 2, 'double'}, ...
         (1 + 3)/2}}, ...
         'allNaN', {{{[NaN, NaN]}, NaN}}, ...
         'allNaNColumn', {{{[NaN, 1; NaN, 3]}, [NaN, (1 + 3)/2]}}, ...
         'empty', {{{[]}, NaN}}, ...
         'emptyMatrix', {{{zeros(0, 3)}, NaN(1, 3)}})

      % nanmedian cases. Each case holds the input arguments and the
      % expected median. nanmedian ignores NaN elements in column and row
      % vectors. A matrix takes medians down columns by default and along
      % DIM when given. All-NaN and empty inputs return NaN.
      mediancase = struct( ...
         'column', {{{[3; NaN; 1; 2]}, 2}}, ...
         'row', {{{[4, NaN, 1]}, (1 + 4)/2}}, ...
         'matrixDefaultDim', {{{[1, NaN, 5; 3, 4, 6; NaN, 8, 9]}, ...
         [(1 + 3)/2, (4 + 8)/2, 6]}}, ...
         'matrixDim2', {{{[1, NaN, 5; 3, 4, 6; NaN, 8, 9], 2}, ...
         [(1 + 5)/2; 4; (8 + 9)/2]}}, ...
         'allNaN', {{{[NaN; NaN]}, NaN}}, ...
         'empty', {{{[]}, NaN}})

      % Input counts outside the narginchk range. Each case holds the
      % function name, the input arguments, and the expected error
      % identifier. nanmean accepts one to three inputs; nanmedian accepts
      % one or two.
      badcount = struct( ...
         'nanmeanNone', {{'nanmean', {}, ...
         'MATLAB:narginchk:notEnoughInputs'}}, ...
         'nanmeanFour', {{'nanmean', {[1, 2], 2, 'double', 'omitnan'}, ...
         'MATLAB:narginchk:tooManyInputs'}}, ...
         'nanmedianNone', {{'nanmedian', {}, ...
         'MATLAB:narginchk:notEnoughInputs'}}, ...
         'nanmedianThree', {{'nanmedian', {[1, 2], 2, 1}, ...
         'MATLAB:narginchk:tooManyInputs'}})
   end

   properties
      % The private nanmean and nanmedian function handles.
      nanmean
      nanmedian
   end

   methods (TestClassSetup)
      function getfunctions(testCase)
         % Store the private function handles once for every test.
         testCase.nanmean = baseflow.privatefunction('nanmean');
         testCase.nanmedian = baseflow.privatefunction('nanmedian');
      end
   end

   methods (Test)
      function test_nanmean(testCase, meancase)
         % nanmean returns the mean of the non-NaN elements.
         [args, expected] = meancase{:};
         returned = testCase.nanmean(args{:});
         testCase.verifyEqual(returned, expected)
      end

      function test_nanmedian(testCase, mediancase)
         % nanmedian returns the median of the non-NaN elements.
         [args, expected] = mediancase{:};
         returned = testCase.nanmedian(args{:});
         testCase.verifyEqual(returned, expected)
      end

      function test_inputCount(testCase, badcount)
         % An input count outside the narginchk range raises its error.
         [funcname, args, errid] = badcount{:};
         func = testCase.(funcname);
         testCase.verifyError(@() func(args{:}), errid)
      end
   end
end
