classdef test_fitopts < matlab.unittest.TestCase
   %TEST_FITOPTS Test the fitab fitopts pass-through.
   %
   % fitopts fields override the same-named fitab name-value options, and
   % fitevents passes the struct to fitab. An unknown field or a wrong type
   % is an error, so fitab never ignores a fitopts field.

   properties
      % Synthetic recession data that every fitab call fits.
      q
      dqdt
   end

   properties (TestParameter)
      % Each case pairs a fit method and a fitopts struct with the named
      % options that produce the same fit. The scalarDefaults case expects
      % the fit with no options: weights 1 and mask true are the scalar
      % defaults, and the overrides apply before the scalar expansion. The
      % scalarWeight case expects the unweighted fit, because a uniform
      % weight does not change a least-squares fit.
      Override = struct( ...
         'quantile', struct('method', 'qtl', ...
            'fitopts', struct('quantile', 0.3), ...
            'namedargs', {{'quantile', 0.3}}), ...
         'multiField', struct('method', 'qtl', ...
            'fitopts', struct('quantile', 0.3, 'Nboot', 50, ...
               'alpha', 0.9, 'order', 1), ...
            'namedargs', {{'quantile', 0.3, 'Nboot', 50, ...
               'alpha', 0.9, 'order', 1}}), ...
         'scalarDefaults', struct('method', 'nls', ...
            'fitopts', struct('weights', 1, 'mask', true), ...
            'namedargs', {{}}), ...
         'scalarWeight', struct('method', 'ols', ...
            'fitopts', struct('weights', 0.5), ...
            'namedargs', {{}}));

      % Each case passes an invalid fitopts struct to fitab with the error
      % it must raise: an unknown field, or a wrong type for each field.
      Invalid = struct( ...
         'unknownField', struct('fitopts', struct('nosuchoption', 1), ...
            'errorid', 'baseflow:fitab:unknownFitopt'), ...
         'charWeights', struct('fitopts', struct('weights', 'x'), ...
            'errorid', 'baseflow:fitab:invalidFitopt'), ...
         'charOrder', struct('fitopts', struct('order', 'x'), ...
            'errorid', 'baseflow:fitab:invalidFitopt'), ...
         'numericMask', struct('fitopts', struct('mask', 1), ...
            'errorid', 'baseflow:fitab:invalidFitopt'), ...
         'charQuantile', struct('fitopts', struct('quantile', 'x'), ...
            'errorid', 'baseflow:fitab:invalidFitopt'), ...
         'charRefqtls', struct('fitopts', struct('refqtls', 'x'), ...
            'errorid', 'baseflow:fitab:invalidFitopt'), ...
         'charNboot', struct('fitopts', struct('Nboot', 'x'), ...
            'errorid', 'baseflow:fitab:invalidFitopt'), ...
         'charAlpha', struct('fitopts', struct('alpha', 'x'), ...
            'errorid', 'baseflow:fitab:invalidFitopt'), ...
         'numericPlotfit', struct('fitopts', struct('plotfit', 1), ...
            'errorid', 'baseflow:fitab:invalidFitopt'));

      % Only a scalar weights or mask applies to every event fit in
      % fitevents; a vector or an empty value is an error.
      NonscalarFitopt = struct( ...
         'vectorWeights', struct('weights', [1; 2]), ...
         'vectorMask', struct('mask', [true; false]), ...
         'emptyWeights', struct('weights', []));
   end

   methods (TestClassSetup)
      function makeRecessionData(testCase)
         %MAKERECESSIONDATA Generate the data once for all tests.

         % Nonlinear (b = 1.5) synthetic recession data for the fits.
         a = 1e-2;
         b = 1.5;
         q0 = 100;
         t = 1:100;
         [~, testCase.q, testCase.dqdt] = ...
            baseflow.generateTestData(a, b, q0, t);
      end
   end

   methods (Test)
      function test_overrideMatchesNamedOptions(testCase, Override)
         %TEST_OVERRIDEMATCHESNAMEDOPTIONS fitopts fields equal named options.

         % fit once with fitopts and once with the matching named options;
         % the tolerance allows round-off from a uniform weight
         tol = 1e-10;
         returned = baseflow.fitab(testCase.q, testCase.dqdt, ...
            Override.method, 'fitopts', Override.fitopts);
         expected = baseflow.fitab(testCase.q, testCase.dqdt, ...
            Override.method, Override.namedargs{:});
         testCase.verifyEqual(returned.ab, expected.ab, 'RelTol', tol)
      end

      function test_precedenceOverNamedOption(testCase)
         %TEST_PRECEDENCEOVERNAMEDOPTION fitopts overrides a named option.

         % A fitopts field overrides the same-named option in the same call.
         returned = baseflow.fitab(testCase.q, testCase.dqdt, 'qtl', ...
            'quantile', 0.1, 'fitopts', struct('quantile', 0.3));
         expected = baseflow.fitab(testCase.q, testCase.dqdt, 'qtl', ...
            'quantile', 0.3);
         testCase.verifyEqual(returned.ab, expected.ab)
      end

      function test_invalidFitoptsErrors(testCase, Invalid)
         %TEST_INVALIDFITOPTSERRORS An invalid fitopts field is an error.

         % an unknown field or a wrong type raises the documented error
         testCase.verifyError(@() baseflow.fitab(testCase.q, ...
            testCase.dqdt, 'nls', 'fitopts', Invalid.fitopts), ...
            Invalid.errorid)
      end

      function test_threadsThroughFitevents(testCase)
         %TEST_THREADSTHROUGHFITEVENTS fitevents forwards fitopts to fitab.

         % fitevents forwards fitopts into its fitab calls, and setopts accepts
         % the documented option. An unknown field raises the fitab error
         % through fitevents.
         [T, Q, R] = baseflow.loadExampleData();
         opts = baseflow.setopts('getevents');
         EventData = baseflow.getevents(T, Q, R, opts);
         fitopts = baseflow.setopts('fitevents', ...
            'fitopts', struct('nosuchoption', 1));
         testCase.verifyError(@() baseflow.fitevents(EventData, fitopts), ...
            'baseflow:fitab:unknownFitopt')
      end

      function test_fiteventsRejectsNonscalarFitopt(testCase, ...
            NonscalarFitopt)
         %TEST_FITEVENTSREJECTSNONSCALARFITOPT fitevents needs scalar options.

         % The check runs during input parsing, so no event data is needed.
         testCase.verifyError(@() baseflow.fitevents(struct(), ...
            'fitopts', NonscalarFitopt), 'baseflow:fitevents:nonscalarFitopt')
      end
   end
end
