% +DEPS
% 
%   Contents file for +DEPS and its subfolders.
%   
%   +DEPS
%   baseflow.deps.arrow       - Draw a line with an arrowhead
%   baseflow.deps.derivative  - Compute derivative while preserving dimensions
%   baseflow.deps.deta        - Calculate Dirichlet functions of the form f = sum((-1)^n/(k*n+1)^z)
%   baseflow.deps.ginputc     - Graphical input from mouse
%   baseflow.deps.hline       - Draw a horizontal line on the current axes at specified location
%   baseflow.deps.ktaub       - Mann-Kendall Tau (aka Tau-b) with Sen's Method (enhanced)
%   baseflow.deps.movingslope - Estimate local slope from point sequence using a sliding window
%   baseflow.deps.peakfinder  - Noise tolerant fast peak finding algorithm
%   baseflow.deps.plfit       - Fit a power-law distributional model to data
%   baseflow.deps.plotboxpos  - Returns the position of the plotted axis region
%   baseflow.deps.plvar       - Estimate the uncertainty in the estimated power-law parameters
%   baseflow.deps.rsquare     - Compute coefficient of determination of data fit model and RMSE
%   baseflow.deps.tsregr      - Theil-Sen estimator
%   baseflow.deps.zeta        - Riemann Zeta function
%    
%   This file was generated by updatecontents.m on 06 Sep 2023 at 15:36:12.
