% +INTERNAL
% 
%   Contents file for +INTERNAL and its subfolders.
%   
%   +INTERNAL
%   baseflow.internal.basepath                   - Return toolbox basepath
%   baseflow.internal.buildpath                  - Build full path to toolbox folder or file
%   baseflow.internal.completions                - Generate function auto-completions for string literals
%   baseflow.internal.dependencies               - Generate function and product dependencies for function
%   baseflow.internal.docpath                    - Return path to toolbox doc file
%   baseflow.internal.makecontents               - Make contents.m for each toolbox folder including packages
%   baseflow.internal.makedocs                   - Publish GettingStarted.m as index.html for GitPages
%   baseflow.internal.replacePackagePrefix       - Replace namespace package prefix in function files
%   baseflow.internal.runtests                   - Run all tests in the test suite
%   baseflow.internal.showpath                   - Show the output of projectpath() and toolboxpath() to verify
%   baseflow.internal.version                    - Return the version number for the baseflow toolbox
%   
%   +INTERNAL/PRIVATE
%   baseflow.internal/private.backupfile         - Create a backup file name or folder name and (optionally) a copy
%   baseflow.internal/private.cellmap            - Apply function to cell-array
%   baseflow.internal/private.closeifpublishing  - Close figure only if script is being published
%   baseflow.internal/private.convertlivescripts - Convert live script to m-files
%   baseflow.internal/private.getcontents        - Get the contents of a specified directory
%   baseflow.internal/private.getinstallpath     - Return toolbox installation path
%   baseflow.internal/private.ispublishing       - True if this script is currently being published
%   baseflow.internal/private.listfiles          - List all files in folder and (optionally) subfolders
%   baseflow.internal/private.listfolders        - Return a list of folders under a top-level directory
%   baseflow.internal/private.mpackagefolders    - List all package and sub-package folders in folder
%   baseflow.internal/private.projectpath        - Return project basepath
%   baseflow.internal/private.snapnowandclose    - Call SNAPNOW and CLOSE only if script is being published
%   baseflow.internal/private.toolboxpath        - Return toolbox basepath
%   baseflow.internal/private.updatecontents     - Create a Contents.m file including subdirectories
%   baseflow.internal/private.withcd             - Temporarily cd to a directory
%    
%   This file was generated by updatecontents.m on 20 Sep 2023 at 14:08:07.
