% +TEST
% 
%   Contents file for +TEST and its subfolders.
%   
%   +TEST
%   bfra.test.runtests         - Run all tests in the bfra.test package
%   bfra.test.test_conversions - Test bfra.conversions
%   bfra.test.test_islocalmax  - Test bfra/private/islocalmax.m
%   bfra.test.test_todatenum   - Test bfra/private/todatenum
%   bfra.test.test_withcd      - Test withcd
%   bfra.test.TestBaseflow     - Test the baseflow toolbox
%    
%   This file was generated by updatecontents.m on 06 Sep 2023 at 15:36:12.
