Description of open
Home > +baseflow > open.m
open
PURPOSE
OPEN Open package namespace function file in the Editor.
SYNOPSIS
function open(varargin)
DESCRIPTION
OPEN Open package namespace function file in the Editor.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
QtString QTSTRING Return latex-formatted string for Q(t) function.
QtauString QTAUSTRING Return latex-formatted string for Q(tau) function.
aquiferprops AQUIFERPROPS Estimate aquifer depth, hydraulic conductivity, and porosity.
aquiferstorage AQUIFERSTORAGE Estimate aquifer storage from recession event parameters.
aquiferthickness AQUIFERTHICKNESS Estimate aquifer thickness from recession event parameters.
aquifertrend AQUIFERTREND Estimate the linear trend in saturated aquifer thickness.
baseflowtrend BASEFLOWTREND Estimate baseflow trend from annual streamflow timeseries.
basinname BASINNAME Return string 'basin' from the baseflow basin database.
characteristicTime CHARACTERISTICTIME compute the characteristic e-folding time for baseflow
checkevent CHECKEVENT plot detected recession event and fitted values
cloudphi CLOUDPHI Estimate drainable porosity phi from the point cloud.
conversions CONVERSIONS convert inputvalue of inputvarname to the value of outputvarname
dndtuncertainty DNDTUNCERTAINTY Compute combined uncertainty of the dn/dt trend estimate.
eventfinder EVENTFINDER find recession events using hydrograph and rainfall timeseries.
eventphi EVENTPHI estimate drainable porosity phi from individual recession events
eventpicker EVENTPICKER Automated or user-guided recession event selection.
eventplotter EVENTPLOTTER plot recession events detected by eventfinder
eventtau EVENTTAU Compute drainage timescale tau from event-scale parameters a and b.
expectedQ EXPECTEDQ Compute the expected value of baseflow.
fdcurve FDCURVE Compute a flow duration curve from streamflow timeseries.
fitab FITAB fit event-scale recession equation -dq/dt = aQ^b
fitevents FITEVENTS Wrapper around getdqdt and fitdqdt functions to fit all events.
fitphi FITPHI Estimate drainable porosity using early- and late-time solutions.
fitphidist FITPHIDIST fit drainable porosity (phi) values with a Beta distribution
getdqdt GETDQDT Numerical estimation of the time derivative of discharge dQ/dt.
getevents GETEVENTS Get recession events from daily hydrograph timeseries T, Q, and R.
getfunction GETFUNCTION get function handle from the baseflow function library
getstring GETSTRING Get latex-formatted string for equations in the baseflow library.
globalfit GLOBALFIT Fit global parameters using all event-scale recession fits.
gpfitb GPFITB Fit Generalized Pareto Distribution to recession parameter tau.
hyetograph HYETOGRAPH Plot a discharge rainfall hyetograph.
loadbasins LOADBASINS Load boundary object for basin specified by basinname.
loadcalm LOADCALM Load CALM ALT data for a basin in the Bounds struct.
loadflow LOADFLOW Load timeseries of streamflow and metadata for basin.
loadghcnd LOADGHCND Read in a global hydroclimatology network database file.
loadgrace LOADGRACE Load grace data for basin in baseflow basin database.
loadmeta LOADMETA Load metadata for basin indicated by basinname.
loadprops LOADPROPS Load basin properties from metadata table.
mapbasins MAPBASINS Map basin boundaries and color their faces by an attribute.
mapgages MAPGAGES map a set of gage locations and color their faces by an attribute
phifitensemble PHIFITENSEMBLE Fit phi estimate ensemble using all recession events in Fits.
plfitb PLFITB fit an unbounded Pareto Distribution to recession parameter tau
plotaquifertrend PLOTAQUIFERTREND Plot the saturated aquifer thickness trend.
plotdqdt PLOTDQDT Plot the log-log q vs dq/dt point-cloud
plotrefline PLOTREFLINE Add a reference line to a point cloud plot.
plplotb PLPLOTB Plot the power law fit to the P(tau) pareto distribution.
pointcloudintercept POINTCLOUDINTERCEPT Estimate parameter 'a' from the point cloud intercept.
pointcloudplot POINTCLOUDPLOT Plot a point-cloud diagram to estimate aquifer parameters.
setopts SETOPTS Set algorithm options for functions getevents, fitevents, globalfit.
specialfunctions SPECIALFUNCTIONS Special function ibarary required for recession analysis.
wrapevents WRAPEVENTS Detect recession events on an annual calendar basis.
SOURCE CODE
function open(varargin)
   %OPEN Open package namespace function file in the Editor.
   narginchk(1,1)
   funcname = validatestring(varargin{1}, baseflow.internal.completions('open'));
   edit(fullfile(baseflow.internal.buildpath('+baseflow'), funcname))
end