% +UTIL
% 
%   Contents file for +UTIL and its subfolders.
%   
%   +UTIL
%   baseflow.util.numevents - Count the number of events in struct returned by baseflow.getevents
%   baseflow.util.numfits   - Count the number of fits in struct returned by baseflow.fitevents
%   baseflow.util.numtau    - Count the number of tau values in struct returned by baseflow.fitevents
%    
%   This file was generated by updatecontents.m on 12 Sep 2023 at 00:41:17.
