% +UTIL
% 
%   Contents file for +UTIL and its subfolders.
%   
%   +UTIL
%   baseflow.util.numevents - Count the number of events in EventData returned by baseflow.getevents
%   baseflow.util.numfits   - Count the number of fits in EventFits returned by baseflow.fitevents
%   baseflow.util.numtau    - Count the number of tau values in struct returned by baseflow.fitevents
%    
%   This file was generated by updatecontents.m on 13 Sep 2026 at 16:08:24.
