Description of version
Home > +bfra > version.m
version
PURPOSE
VERSION return the version number for the baseflow toolbox
SYNOPSIS
function varargout = version()
DESCRIPTION
VERSION return the version number for the baseflow toolbox
  v = version()
 See also:
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
loadbasins LOADBASINS Load boundary object for basin specified by basinname.
loadcalm LOADCALM Load CALM ALT data for a basin in the Bounds struct.
loadmeta LOADMETA Load metadata for basin indicated by basinname.
loadprops LOADPROPS Load basin properties from metadata table.
SOURCE CODE
function varargout = version()
   %VERSION return the version number for the baseflow toolbox
   %
   %  v = version()
   %
   % See also:
   v = '0.1.0';
   if nargout == 1
      varargout{1} = v;
   else
      disp(v);
   end
   home
   disp(' _______                        ___  __                     ')
   disp('|   _   \.---.-..-----..-----..''  _||  |.-----..--.--.--.  ')
   disp('|.  v1  /|  _  ||__ --||  -__||   _||  ||  _  ||  |  |  |   ')
   disp('|.  _   \|___._||_____||_____||__|  |__||_____||________|   ')
   disp('|:  00   \              ____        ______      ______      ')
   disp('|::.. .  /   .--.--.   |_   |      |      |    |      |     ')
   disp('`-------''    |  |  |__  _|  |_  __ |  --  | __ |  --  |    ')
   disp('              \___/|__||______||__||______||__||______|     ')
end